model_type: gravity
dt: 0.1
device: cuda
filter:
  pitch:
    active: False
    min: 0
    max: 0.099
  speed:
    active: False
    min: 0.2
    max: 20
linear:
  params:
    '0': 0.0518
    '1': 0.5874
    '2': -2.2068
    '3': -1.1199
    '4': 2.0
  opt_param_names: 
    - '0'
    - '1'
    - '2'
    - '3'
    # - '4'

  common:  
    vel_clip:
      active: True
      min: -20.
      max: 20

gravity:
  params:
    '0': -0.13
    '1': 0.6247
    '2': -2.1344
    '3': -1.2706
    '4': 2.0
    '5': -0.7
  opt_param_names: 
    - '0'
    - '1'
    - '2'
    - '3'
    - '5'

  common:
    vel_clip:
      active: True
      min: -20.
      max: 20