---
common:
    B: 1           #number of optimizations to run in parallel
    H: 50          #number of timesteps to roll out
    M: 2           #dim of action space
    dt: 0.1        #length of timestep
    device: cpu   #device to run on 

model:
    type: GravityThrottleKBM
    args:
        L: 3.0
        throttle_lim: [0., 1.]
        steer_lim: [-0.52, 0.52]
        steer_rate_lim: 0.3
        actuator_model: [-0.044, 0.5665, -2.0924, -1.5005, 2.0, -0.7938]

    actuator_delay: [5, 0] #num timesteps to delay controls

sampling_strategies:
    strategies:
        - type: ActionLibrary
          label: action_library
          args:
            K: 50
            path: "/home/atv/physics_atv_ws/src/control/torch_mpc/data/action_libraries/yamaha_atv/H75_throttle_steer_unif.pt"

        - type: GaussianWalk
          label: gaussian_walk
          args:
            K: 256
            initial_distribution:
                type: gaussian
                scale: [0.5, 0.0]
            alpha: [0.0, 0.0]   #low-pass on noise
            scale: [0.000, 0.005]  #sample scale on change of noise

cost_function:
    terms:
        - type: SpeedLimit
          weight: 1.0
          args:
            target_speed: 4.5
            max_speed: 5.5

        - type: FootprintSpeedmapProjection
          weight: 0.001
          args:
            shortrange: true
            local_frame: true

        #shortrange map
#        - type: CostmapProjection
#          weight: 5.0
#          args:
#            shortrange: true
#            local_frame: true
#            cost_thresh: 5.

        # - type: FootprintCostmapProjection
        #   weight: 10.0
        #   args:
        #     shortrange: true
        #     local_frame: true
        #     length: 5.0
        #     width: 3.0
        #     length_offset: -1.0
        #     width_offset: 0.0
        #     nl: 5
        #     nw: 5
    
        #smaller footprint for constraint
        - type: FootprintCostmapProjection
          weight: 0.001
          args:
            length: 0.75
            width: 0.75
            length_offset: -1.0
            width_offset: 0.0
            cost_thresh: 5.

        #full footprint for cost eval
        - type: FootprintCostmapProjection
          weight: 1.0
          args:
            length: 5.0
            width: 3.0
            length_offset: -1.0
            width_offset: 0.0
            nl: 5
            nw: 5

        - type: EuclideanDistanceToGoal
          weight: 5.0
          args:

update_rule:
    type: MPPI
    args:
        temperature: 0.1
        
recovery_behavior: []

ros:
    observation:
        "/integrated_to_init":
            type: Odometry
            remap: "state"

        "/ros_talon/current_position":
            type: Float32
            remap: "steer_angle"

        "/gps_pitch":
            type: Float32
            remap: "pitch"

    action:
        "/cmd":
            type: Twist
            options:
                mode: "action"
